### ISSUE TITLE
build failure after commit f20228a67d826408de5b348fe0fbfda1a93ac813 or the following commit

### ISSUE THREAD

**Issue by QMeqGR** [wxMaxima-developers/wxmaxima#2091]
[ 62%] Building CXX object src/CMakeFiles/wxmaxima.dir/cells/ParenCell.cpp.o
/home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:50:23: error: redefinition of ‘std::unique_ptr<Cell> LabelCell::Copy(GroupCell*) const’
   50 | std::unique_ptr<Cell> LabelCell::Copy(GroupCell *group) const {
      |                       ^~~~~~~~~
In file included from /home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:32:
/home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:48:13: note: ‘virtual std::unique_ptr<Cell> LabelCell::Copy(GroupCell*) const’ previously defined here
   48 | DEFINE_CELL(LabelCell)
      |             ^~~~~~~~~
/home/packages/SOURCE/wxmaxima/src/cells/CellImpl.h:46:25: note: in definition of macro ‘DEFINE_CELL_COPY’
   46 |   std::unique_ptr<Cell> type::Copy(GroupCell *group) const      \
      |                         ^~~~
/home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:48:1: note: in expansion of macro ‘DEFINE_CELL’
   48 | DEFINE_CELL(LabelCell)
      | ^~~~~~~~~~~
[ 62%] Building CXX object src/CMakeFiles/wxmaxima.dir/cells/ProductCell.cpp.o
gmake[2]: *** [src/CMakeFiles/wxmaxima.dir/build.make:905: src/CMakeFiles/wxmaxima.dir/cells/LabelCell.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:771: src/CMakeFiles/wxmaxima.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2

and then again later:

[ 27%] Building CXX object src/CMakeFiles/wxmaxima.dir/cells/LabelCell.cpp.o
/home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:50:23: error: redefinition of ‘std::unique_ptr<Cell> LabelCell::Copy(GroupCell*) const’
   50 | std::unique_ptr<Cell> LabelCell::Copy(GroupCell *group) const {
      |                       ^~~~~~~~~
In file included from /home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:32:
/home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:48:13: note: ‘virtual std::unique_ptr<Cell> LabelCell::Copy(GroupCell*) const’ previously defined here
   48 | DEFINE_CELL(LabelCell)
      |             ^~~~~~~~~
/home/packages/SOURCE/wxmaxima/src/cells/CellImpl.h:46:25: note: in definition of macro ‘DEFINE_CELL_COPY’
   46 |   std::unique_ptr<Cell> type::Copy(GroupCell *group) const      \
      |                         ^~~~
/home/packages/SOURCE/wxmaxima/src/cells/LabelCell.cpp:48:1: note: in expansion of macro ‘DEFINE_CELL’
   48 | DEFINE_CELL(LabelCell)
      | ^~~~~~~~~~~
gmake[2]: *** [src/CMakeFiles/wxmaxima.dir/build.make:905: src/CMakeFiles/wxmaxima.dir/cells/LabelCell.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:771: src/CMakeFiles/wxmaxima.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
   +++ Done. +++

**Comment by QMeqGR** [comment]
works for me

**Comment by daute** [comment]
Yes, it worked here (my local PC) too - but I didn't close the ticked immediately, to check, if all CI jobs on different operating systems are finished, and all compiled without problems.
